# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93a4f528caec823f6e7ffbe6d7bcd9006c41ff50fd971946a2e4283ad71e7d06f31718c857ba8de49c089e50df9200ffcbd8cf896ff86cfbcaf130d129d5f583

test:
  secret_key_base: 9d25b575a23a67952b650d37768c4a131b049153fe144c38464aef99a16140ac6c0d14011634de7c8318fd25e192a499ea5eb5144fcc95174409863696677963

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
